### ISSUE TITLE
[Feature Request] Allow passing objects into jobs

### ISSUE THREAD

**Issue by myavchik** [spiral/jobs#21]
Allow passing objects into jobs

```
$queue->push(new SomeJob([
                'user' => $user // User object
            ]));

---------------------------

class SomeJob extends AbstractJob
{
    public function do(User $user)

```

**Comment by wolfy-j** [comment]
Hi,

you are looking at 1.0 API which has been using Laravel style. Take a look at 2.0 described in documentations.

You are still not able to pass objects directly due to conceptual limitations (for example, what PHP User should do in Golang handler?) but you have two clear methods responsible for hydration/extraction of data so you can pack this object into any form you want. https://github.com/spiral/docs/blob/feature/2.0/queue/jobs.md#managing-payloads

**Comment by myavchik** [comment]
Oh... thanks.

**Comment by wolfy-j** [comment]
This feature is exactly the reason why we abandon such jobs design as it becomes impossible to implement rich payload management without a massive amount of magic.

**Comment by wolfy-j** [comment]
* you will have to bump your job dependency to 2.0 in your app and refactor existing handlers. But it's easy, simply change the abstract class name and rename "do" into "invoke".
